// Generated by LiveScript 1.3.1
var calc;
calc = function(parties){
  var seat, consume, sum, sum2, final;
  seat = 34;
  consume = 0;
  sum = parties.reduce(function(a, b){
    return a + b.rate;
  }, 0);
  sum2 = parties.filter(function(it){
    return it.rate >= 5;
  }).reduce(function(a, b){
    return a + b.rate;
  }, 0);
  parties.map(function(it){
    it.rate2 = it.rate < 5
      ? 0
      : Math.round((it.rate / sum2) * 10000) / 10000;
    it.seat = Math.floor(it.rate2 * seat) || 0;
    it.remain = it.rate2 * seat - it.seat;
    return consume += it.seat;
  });
  while (consume < seat) {
    parties.sort(fn$);
    parties[0].seat++;
    parties[0].remain = 0;
    consume++;
  }
  final = parties.filter(function(it){
    return it.seat;
  });
  final.sort(function(a, b){
    return b.seat - a.seat;
  });
  return final.map(function(it){
    return console.log(it.name, it.seat);
  });
  function fn$(a, b){
    return b.remain - a.remain;
  }
};